-- LTx OVERWATCH — Seed IoT Devices (all 6 scenarios)

-- IRON CURTAIN — Defence (12 patrol + 4 vehicles + cameras)
INSERT INTO iot_devices (id, scenario_id, device_type, entity_type, entity_id, metadata) VALUES
  ('IC-PAT-01', 'iron-curtain', 'gps_tracker', 'person', 'PAT-01', '{"callsign": "SGT REEVES", "unit": "Alpha"}'),
  ('IC-PAT-02', 'iron-curtain', 'gps_tracker', 'person', 'PAT-02', '{"callsign": "CPL HAYES", "unit": "Alpha"}'),
  ('IC-PAT-03', 'iron-curtain', 'gps_tracker', 'person', 'PAT-03', '{"callsign": "PTE OKAFOR", "unit": "Alpha"}'),
  ('IC-PAT-04', 'iron-curtain', 'gps_tracker', 'person', 'PAT-04', '{"callsign": "SGT CHEN", "unit": "Bravo"}'),
  ('IC-PAT-05', 'iron-curtain', 'gps_tracker', 'person', 'PAT-05', '{"callsign": "CPL WRIGHT", "unit": "Bravo"}'),
  ('IC-PAT-06', 'iron-curtain', 'gps_tracker', 'person', 'PAT-06', '{"callsign": "PTE SILVA", "unit": "Bravo"}'),
  ('IC-PAT-07', 'iron-curtain', 'gps_tracker', 'person', 'PAT-07', '{"callsign": "LT MASON", "unit": "Charlie"}'),
  ('IC-PAT-08', 'iron-curtain', 'gps_tracker', 'person', 'PAT-08', '{"callsign": "SGT BURKE", "unit": "Charlie"}'),
  ('IC-PAT-09', 'iron-curtain', 'gps_tracker', 'person', 'PAT-09', '{"callsign": "CPL TANAKA", "unit": "Charlie"}'),
  ('IC-PAT-10', 'iron-curtain', 'gps_tracker', 'person', 'PAT-10', '{"callsign": "PTE NOVAK", "unit": "Delta"}'),
  ('IC-PAT-11', 'iron-curtain', 'gps_tracker', 'person', 'PAT-11', '{"callsign": "SGT ALI", "unit": "Delta"}'),
  ('IC-PAT-12', 'iron-curtain', 'gps_tracker', 'person', 'PAT-12', '{"callsign": "CPL DUNN", "unit": "Delta"}'),
  ('IC-VH-01', 'iron-curtain', 'vehicle_tracker', 'vehicle', 'VH-01', '{"type": "Humvee", "callsign": "WARHORSE-1"}'),
  ('IC-VH-02', 'iron-curtain', 'vehicle_tracker', 'vehicle', 'VH-02', '{"type": "Humvee", "callsign": "WARHORSE-2"}'),
  ('IC-VH-03', 'iron-curtain', 'vehicle_tracker', 'vehicle', 'VH-03', '{"type": "APC", "callsign": "IRONSIDE-1"}'),
  ('IC-VH-04', 'iron-curtain', 'vehicle_tracker', 'vehicle', 'VH-04', '{"type": "APC", "callsign": "IRONSIDE-2"}');

-- GREEN CANOPY — Agriculture (24 soil sensors + weather + tractors)
INSERT INTO iot_devices (id, scenario_id, device_type, entity_type, entity_id, metadata) VALUES
  ('GC-SOIL-01', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-01', '{"field": "North", "depth_cm": 30}'),
  ('GC-SOIL-02', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-02', '{"field": "North", "depth_cm": 30}'),
  ('GC-SOIL-03', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-03', '{"field": "North", "depth_cm": 60}'),
  ('GC-SOIL-04', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-04', '{"field": "North", "depth_cm": 60}'),
  ('GC-SOIL-05', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-05', '{"field": "East", "depth_cm": 30}'),
  ('GC-SOIL-06', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-06', '{"field": "East", "depth_cm": 30}'),
  ('GC-SOIL-07', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-07', '{"field": "East", "depth_cm": 60}'),
  ('GC-SOIL-08', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-08', '{"field": "East", "depth_cm": 60}'),
  ('GC-SOIL-09', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-09', '{"field": "South", "depth_cm": 30}'),
  ('GC-SOIL-10', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-10', '{"field": "South", "depth_cm": 30}'),
  ('GC-SOIL-11', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-11', '{"field": "South", "depth_cm": 60}'),
  ('GC-SOIL-12', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-12', '{"field": "South", "depth_cm": 60}'),
  ('GC-SOIL-13', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-13', '{"field": "West", "depth_cm": 30}'),
  ('GC-SOIL-14', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-14', '{"field": "West", "depth_cm": 30}'),
  ('GC-SOIL-15', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-15', '{"field": "West", "depth_cm": 60}'),
  ('GC-SOIL-16', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-16', '{"field": "West", "depth_cm": 60}'),
  ('GC-SOIL-17', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-17', '{"field": "Centre", "depth_cm": 30}'),
  ('GC-SOIL-18', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-18', '{"field": "Centre", "depth_cm": 30}'),
  ('GC-SOIL-19', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-19', '{"field": "Centre", "depth_cm": 60}'),
  ('GC-SOIL-20', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-20', '{"field": "Centre", "depth_cm": 60}'),
  ('GC-SOIL-21', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-21', '{"field": "Greenhouse", "depth_cm": 15}'),
  ('GC-SOIL-22', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-22', '{"field": "Greenhouse", "depth_cm": 15}'),
  ('GC-SOIL-23', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-23', '{"field": "Greenhouse", "depth_cm": 30}'),
  ('GC-SOIL-24', 'green-canopy', 'soil_sensor', 'sensor', 'SOIL-24', '{"field": "Greenhouse", "depth_cm": 30}'),
  ('GC-WX-01', 'green-canopy', 'weather_station', 'sensor', 'WX-01', '{"type": "Davis Vantage Pro"}'),
  ('GC-TR-01', 'green-canopy', 'vehicle_tracker', 'vehicle', 'TRACTOR-01', '{"type": "John Deere 8R"}'),
  ('GC-TR-02', 'green-canopy', 'vehicle_tracker', 'vehicle', 'TRACTOR-02', '{"type": "Fendt 942"}');

-- FIRST LIGHT — Disaster Response (30 survivors + 8 responders + drones)
INSERT INTO iot_devices (id, scenario_id, device_type, entity_type, entity_id, metadata) VALUES
  ('FL-CIV-01', 'first-light', 'biometric_tracker', 'person', 'CIV-001', '{"status": "trapped", "floor": "B1"}'),
  ('FL-CIV-02', 'first-light', 'biometric_tracker', 'person', 'CIV-002', '{"status": "trapped", "floor": "2"}'),
  ('FL-CIV-03', 'first-light', 'biometric_tracker', 'person', 'CIV-003', '{"status": "mobile", "floor": "G"}'),
  ('FL-CIV-04', 'first-light', 'biometric_tracker', 'person', 'CIV-004', '{"status": "trapped", "floor": "3"}'),
  ('FL-CIV-05', 'first-light', 'biometric_tracker', 'person', 'CIV-005', '{"status": "mobile", "floor": "G"}'),
  ('FL-CIV-06', 'first-light', 'biometric_tracker', 'person', 'CIV-006', '{"status": "critical", "floor": "B2"}'),
  ('FL-CIV-07', 'first-light', 'biometric_tracker', 'person', 'CIV-007', '{"status": "trapped", "floor": "1"}'),
  ('FL-CIV-08', 'first-light', 'biometric_tracker', 'person', 'CIV-008', '{"status": "mobile", "floor": "G"}'),
  ('FL-CIV-09', 'first-light', 'biometric_tracker', 'person', 'CIV-009', '{"status": "trapped", "floor": "4"}'),
  ('FL-CIV-10', 'first-light', 'biometric_tracker', 'person', 'CIV-010', '{"status": "critical", "floor": "B1"}'),
  ('FL-RES-01', 'first-light', 'gps_tracker', 'person', 'RES-01', '{"callsign": "MEDIC-1", "role": "paramedic"}'),
  ('FL-RES-02', 'first-light', 'gps_tracker', 'person', 'RES-02', '{"callsign": "MEDIC-2", "role": "paramedic"}'),
  ('FL-RES-03', 'first-light', 'gps_tracker', 'person', 'RES-03', '{"callsign": "RESCUE-1", "role": "SAR"}'),
  ('FL-RES-04', 'first-light', 'gps_tracker', 'person', 'RES-04', '{"callsign": "RESCUE-2", "role": "SAR"}'),
  ('FL-RES-05', 'first-light', 'gps_tracker', 'person', 'RES-05', '{"callsign": "ENGINEER-1", "role": "structural"}'),
  ('FL-RES-06', 'first-light', 'gps_tracker', 'person', 'RES-06', '{"callsign": "K9-UNIT", "role": "detection"}'),
  ('FL-RES-07', 'first-light', 'gps_tracker', 'person', 'RES-07', '{"callsign": "COMMAND-1", "role": "IC"}'),
  ('FL-RES-08', 'first-light', 'gps_tracker', 'person', 'RES-08', '{"callsign": "TRIAGE-1", "role": "medical"}'),
  ('FL-DR-01', 'first-light', 'drone_tracker', 'drone', 'DRONE-01', '{"type": "DJI Matrice 350", "payload": "thermal"}'),
  ('FL-DR-02', 'first-light', 'drone_tracker', 'drone', 'DRONE-02', '{"type": "DJI Matrice 350", "payload": "lidar"}');

-- DEEP BLUE — Maritime (15 AIS vessels + patrol boats)
INSERT INTO iot_devices (id, scenario_id, device_type, entity_type, entity_id, metadata) VALUES
  ('DB-VS-01', 'deep-blue', 'ais_transponder', 'vessel', 'VESSEL-01', '{"mmsi": "235009840", "name": "HIGHLAND GUARDIAN", "type": "Cargo"}'),
  ('DB-VS-02', 'deep-blue', 'ais_transponder', 'vessel', 'VESSEL-02', '{"mmsi": "235018560", "name": "NORTH SEA PIONEER", "type": "Tanker"}'),
  ('DB-VS-03', 'deep-blue', 'ais_transponder', 'vessel', 'VESSEL-03', '{"mmsi": "235022470", "name": "ABERDEEN STAR", "type": "Cargo"}'),
  ('DB-VS-04', 'deep-blue', 'ais_transponder', 'vessel', 'VESSEL-04', '{"mmsi": "235031280", "name": "CELTIC DAWN", "type": "Fishing"}'),
  ('DB-VS-05', 'deep-blue', 'ais_transponder', 'vessel', 'VESSEL-05', '{"mmsi": "235045690", "name": "OCEAN ENDURANCE", "type": "Supply"}'),
  ('DB-VS-06', 'deep-blue', 'ais_transponder', 'vessel', 'VESSEL-06', '{"mmsi": "235058120", "name": "GRANITE CITY", "type": "Cargo"}'),
  ('DB-VS-07', 'deep-blue', 'ais_transponder', 'vessel', 'VESSEL-07', '{"mmsi": "235067430", "name": "DEE VOYAGER", "type": "Tanker"}'),
  ('DB-VS-08', 'deep-blue', 'ais_transponder', 'vessel', 'VESSEL-08', '{"mmsi": "235078940", "name": "SHETLAND PRIDE", "type": "Fishing"}'),
  ('DB-VS-09', 'deep-blue', 'ais_transponder', 'vessel', 'VESSEL-09', '{"mmsi": "235089350", "name": "MORAY FIRTH", "type": "Supply"}'),
  ('DB-VS-10', 'deep-blue', 'ais_transponder', 'vessel', 'VESSEL-10', '{"mmsi": "235094760", "name": "PETERHEAD LASS", "type": "Fishing"}'),
  ('DB-VS-11', 'deep-blue', 'ais_transponder', 'vessel', 'VESSEL-11', '{"mmsi": "235105170", "name": "BUCHAN DEEP", "type": "Research"}'),
  ('DB-VS-12', 'deep-blue', 'ais_transponder', 'vessel', 'VESSEL-12', '{"mmsi": "235116580", "name": "FORTIES CHARLIE", "type": "Standby"}'),
  ('DB-VS-13', 'deep-blue', 'ais_transponder', 'vessel', 'VESSEL-13', '{"mmsi": "235127990", "name": "BRAEMAR WAVE", "type": "Cargo"}'),
  ('DB-VS-14', 'deep-blue', 'ais_transponder', 'vessel', 'VESSEL-14', '{"mmsi": "235138400", "name": "RATTRAY HEAD", "type": "Tanker"}'),
  ('DB-VS-15', 'deep-blue', 'ais_transponder', 'vessel', 'VESSEL-15', '{"mmsi": "235149810", "name": "DONSIDE EAGLE", "type": "Supply"}'),
  ('DB-PT-01', 'deep-blue', 'gps_tracker', 'vessel', 'PATROL-01', '{"type": "Patrol Boat", "name": "HARBOUR WATCH"}'),
  ('DB-PT-02', 'deep-blue', 'gps_tracker', 'vessel', 'PATROL-02', '{"type": "Patrol Boat", "name": "COAST GUARD 7"}');

-- WILD PULSE — Wildlife (8 elephants + 6 rhinos + rangers)
INSERT INTO iot_devices (id, scenario_id, device_type, entity_type, entity_id, metadata) VALUES
  ('WP-EL-01', 'wild-pulse', 'wildlife_collar', 'animal', 'ELPH-01', '{"species": "African Elephant", "name": "Makena", "sex": "F", "age": 35}'),
  ('WP-EL-02', 'wild-pulse', 'wildlife_collar', 'animal', 'ELPH-02', '{"species": "African Elephant", "name": "Tembo", "sex": "M", "age": 42}'),
  ('WP-EL-03', 'wild-pulse', 'wildlife_collar', 'animal', 'ELPH-03', '{"species": "African Elephant", "name": "Amara", "sex": "F", "age": 28}'),
  ('WP-EL-04', 'wild-pulse', 'wildlife_collar', 'animal', 'ELPH-04', '{"species": "African Elephant", "name": "Kibwe", "sex": "M", "age": 19}'),
  ('WP-EL-05', 'wild-pulse', 'wildlife_collar', 'animal', 'ELPH-05', '{"species": "African Elephant", "name": "Zuri", "sex": "F", "age": 22}'),
  ('WP-EL-06', 'wild-pulse', 'wildlife_collar', 'animal', 'ELPH-06', '{"species": "African Elephant", "name": "Jabari", "sex": "M", "age": 15}'),
  ('WP-EL-07', 'wild-pulse', 'wildlife_collar', 'animal', 'ELPH-07', '{"species": "African Elephant", "name": "Nia", "sex": "F", "age": 31}'),
  ('WP-EL-08', 'wild-pulse', 'wildlife_collar', 'animal', 'ELPH-08', '{"species": "African Elephant", "name": "Kofi", "sex": "M", "age": 26}'),
  ('WP-RH-01', 'wild-pulse', 'wildlife_collar', 'animal', 'RHINO-01', '{"species": "Black Rhino", "name": "Kito", "sex": "M", "age": 18}'),
  ('WP-RH-02', 'wild-pulse', 'wildlife_collar', 'animal', 'RHINO-02', '{"species": "Black Rhino", "name": "Bahati", "sex": "F", "age": 14}'),
  ('WP-RH-03', 'wild-pulse', 'wildlife_collar', 'animal', 'RHINO-03', '{"species": "Black Rhino", "name": "Simba", "sex": "M", "age": 22}'),
  ('WP-RH-04', 'wild-pulse', 'wildlife_collar', 'animal', 'RHINO-04', '{"species": "White Rhino", "name": "Nala", "sex": "F", "age": 12}'),
  ('WP-RH-05', 'wild-pulse', 'wildlife_collar', 'animal', 'RHINO-05', '{"species": "White Rhino", "name": "Asante", "sex": "M", "age": 16}'),
  ('WP-RH-06', 'wild-pulse', 'wildlife_collar', 'animal', 'RHINO-06', '{"species": "White Rhino", "name": "Zawadi", "sex": "F", "age": 9}'),
  ('WP-RG-01', 'wild-pulse', 'gps_tracker', 'person', 'RANGER-01', '{"callsign": "ALPHA LEAD", "unit": "Anti-Poaching"}'),
  ('WP-RG-02', 'wild-pulse', 'gps_tracker', 'person', 'RANGER-02', '{"callsign": "BRAVO LEAD", "unit": "Anti-Poaching"}'),
  ('WP-RG-03', 'wild-pulse', 'gps_tracker', 'person', 'RANGER-03', '{"callsign": "CHARLIE LEAD", "unit": "Patrol"}'),
  ('WP-RG-04', 'wild-pulse', 'gps_tracker', 'person', 'RANGER-04', '{"callsign": "VET-1", "unit": "Veterinary"}');

-- BLACK GOLD — Oil & Gas (20 pressure sensors + patrol vehicles)
INSERT INTO iot_devices (id, scenario_id, device_type, entity_type, entity_id, metadata) VALUES
  ('BG-PIPE-01', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-001', '{"segment": "S1", "depth_m": 85}'),
  ('BG-PIPE-02', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-002', '{"segment": "S1", "depth_m": 85}'),
  ('BG-PIPE-03', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-003', '{"segment": "S1", "depth_m": 90}'),
  ('BG-PIPE-04', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-004', '{"segment": "S2", "depth_m": 92}'),
  ('BG-PIPE-05', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-005', '{"segment": "S2", "depth_m": 95}'),
  ('BG-PIPE-06', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-006', '{"segment": "S2", "depth_m": 88}'),
  ('BG-PIPE-07', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-007', '{"segment": "S2", "depth_m": 91}'),
  ('BG-PIPE-08', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-008', '{"segment": "S3", "depth_m": 100}'),
  ('BG-PIPE-09', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-009', '{"segment": "S3", "depth_m": 105}'),
  ('BG-PIPE-10', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-010', '{"segment": "S3", "depth_m": 98}'),
  ('BG-PIPE-11', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-011', '{"segment": "S3", "depth_m": 102}'),
  ('BG-PIPE-12', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-012', '{"segment": "S4", "depth_m": 110}'),
  ('BG-PIPE-13', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-013', '{"segment": "S4", "depth_m": 108}'),
  ('BG-PIPE-14', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-014', '{"segment": "S4", "depth_m": 115}'),
  ('BG-PIPE-15', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-015', '{"segment": "S5", "depth_m": 120}'),
  ('BG-PIPE-16', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-016', '{"segment": "S5", "depth_m": 118}'),
  ('BG-PIPE-17', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-017', '{"segment": "S5", "depth_m": 125}'),
  ('BG-PIPE-18', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-018', '{"segment": "S6", "depth_m": 130}'),
  ('BG-PIPE-19', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-019', '{"segment": "S6", "depth_m": 128}'),
  ('BG-PIPE-20', 'black-gold', 'pressure_sensor', 'sensor', 'PIPE-020', '{"segment": "S6", "depth_m": 135}'),
  ('BG-VH-01', 'black-gold', 'vehicle_tracker', 'vehicle', 'PATROL-V1', '{"type": "Inspection Vessel", "name": "SENTINEL"}'),
  ('BG-VH-02', 'black-gold', 'vehicle_tracker', 'vehicle', 'PATROL-V2', '{"type": "ROV Support", "name": "DEEPWATCH"}');
